#
# Survival Tool
# @author yamagami2211
#

#
# ログイン・ログアウトなどのメッセージを変更できます。
# &でカラーコード
# %playerでプレイヤーの名前
# %nで改行ができます。
#

#権限がないと何もできない系
#ブロックの設置破壊やチャットなどが"権限がない"とできなくなります。
#ログインしてから一定時間経たないと開放されないとかにご利用ください。
Ignore: false

Msg:
  Join: "&a&l%player &rがログインしました。"
  FJoin: "&a&l%player &rが初めてログインしました。"
  Quit: "&a&l%player &rがログアウトしました。"
  Inv: "%playerのインベントリーを開きました。"
  Ender: "%playerのエンダーチェストを開きました。"
  OfErr: "%player はオフラインです。"

home:
  tp: "&6Homeに設定した場所にTPしました。"
  set: "&3現在座標をHomeに記録しました。"
  nottp: "&4Homeが設定されていません。"

ReSpawn:
  tp: "&6リスポーンポイントにTPしました。"
  notp: "&4ベットもしくはリスポーンアンカーが存在しないもしくは塞がれているためTPできません。"

Death:
  tp: "&6死亡したポイントにTPしました"
  notp: "&4死亡したポイントが記録されていません。"

#Msg は自分用
#Msg2は他プレイヤを対象にした場合です。
Ping:
  Msg: "&6Ping: %Ping ms"
  Msg2: "&6 %player の Ping: %Ping ms"

Gamemode:
  Survival: "サバイバルに変更しました"
  Creative: "クリエイティブに変更しました"
  Adventure: "アドベンチャーに変更しました"
  Spectator: "スペクテイターに変更しました"

plugin:
  reload: "&aConfigをリロードしました。"
  notpex: "&4権限がありません。"
  notgame: "&4ゲーム内から実行してください。"

#
# homeの設定はhome.ymlに記録されています。
# 死亡したポイントがdeathP.ymlに記録されています。
#