name: SurvivalTool
version: ${project.version}
main: jp.yama2211.st.Main
api-version: 1.16

commands:
  st:
    description: プラグインのヘルプコマンドです。
  st.reload:
    description: configをリロードするコマンドです。
  home:
    description: 設定した場所にTPできるコマンドです。
  home.set:
    description: 現在の座標を記録します。
  respawn:
    description: ベットなどのスポーンポイントにTPします。
  death:
    description: 直前の死亡したポイントにTPします。
  skull:
    description: プレイヤーの頭を入手できます。

permissions:
  home.use:
    default: true
  respawn.use:
    default: true
  skull.get:
    default: true
  death.use:
    default: true
  st.admin:
    default: op