name: SurvivalTool
version: ${project.version}
main: jp.yama2211.st.Main
api-version: 1.16

commands:
  st:
    description: プラグインのヘルプコマンドです。
  st.reload:
    description: configをリロードするコマンドです。
  home:
    description: 設定した場所にTPできるコマンドです。
  home.set:
    description: 現在の座標を記録します。
  respawn:
    description: ベットなどのスポーンポイントにTPします。
  death:
    description: 直前の死亡したポイントにTPします。
  skull:
    description: プレイヤーの頭を入手できます。

permissions:
  home.use:
    default: true
  respawn.use:
    default: true
  skull.get:
    default: true
  death.use:
    default: true
  st.admin:
    default: op
  st.ignore.chat:
    default: op
  st.ignore.blockbreak:
    default: op
  st.ignore.blockplace:
    default: op
  st.ignore.itemdrop:
    default: op
  st.ignore.itempickup:
    default: op
  st.arrowpickup.ignore:
    default: op
  st.ignore.inventory.chest:
    default: op
  st.ignore.inventory.enderchest:
    default: op
  st.ignore.*:
    children:
      st.ignore.chat: true
      st.ignore.blockbreak: true
      st.ignore.blockplace: true
      st.ignore.itemdrop: true
      st.ignore.itempickup: true
      st.ignore.inventory.chest: true
      st.ignore.inventory.enderchest: true